name: MasterDeployCI

on:
  push:
    branches:
      - release
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: cd web/ && npm install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email ${{secrets.EMAIL}}
        git config --global user.name ${{secrets.USERNAME}}
        git remote set-url origin https://${{secrets.PERSONAL_ACCESS_TOKEN}}@github.com/${{secrets.USERNAME}}/NLW-1.git
        cd web/ && npm run deploy
    - name: Updating Domain
      run: echo "update domain"
    
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.0.4
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}} #Must be unique in Heroku
          heroku_email: ${{secrets.EMAIL}}
          branch: "release" #OPTIONAL and DEFAULT - 'HEAD' (a.k.a your current branch)
          appdir: "server" #OPTIONAL and DEFAULT - "". This is useful if the api you're deploying is in a subfolder

